<h1><?= $tytul ?></h1>
<style>
    #msg{
        width: 600px;
    }
    h4{
        color: red;
        font-style: italic;
    }
</style>
<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>
        <div id='msg'><h4><?=$msg?></h4></div>
        <table>
        <tr>
            <th>Id:</th>
            <td><?=$autor['id']?></td>
        </tr>
        <tr>
            <th>Imię:</th>
            <td><?=$autor['imie']?></td>
        </tr>
        <tr>
            <th>Nazwisko:</th>
            <td><?=$autor['nazwisko']?></td>
        </tr>
        </table>

        <?= $this->formSubmit($form->get('zapisz')) ?>
        <?= $this->form()->closeTag($form) ?>
    </div>
</div>