<?php
    $typ_nieruchomosci = "";
    if(($oferta->typ_nieruchomosci) == 'M') $typ_nieruchomosci = "mieszkanie";
    else if(($oferta->typ_nieruchomosci) == 'D') $typ_nieruchomosci = "dom";
    else $typ_nieruchomosci = "grunt";

    $typ_oferty = "";
    if(($oferta->typ_oferty) == 'S') $typ_oferty = "sprzedaż";
    else $typ_oferty = "wynajem";
?>
<h2>Szczegóły oferty <?= $oferta->numer ?></h2>
<table style="width:100%">
  <tr>
    <th>Typ oferty:</th>
    <th><?=$typ_oferty?></th>
  </tr>
  <tr>
    <th>Typ nieruchomości::</th>
    <th><?=$typ_nieruchomosci?></th>
  </tr>
  <tr>
    <th>Powierzchnia:</th>
    <th><?=$oferta->powierzchnia?></th>
  </tr>
  <tr>
    <th>Cena:</th>
    <th><?=$oferta->cena?></th>
  </tr>
</table>