<?php
$this->headScript()->appendFile($this->basePath('/js/oferty.js'));
?>
<h1>Koszyk</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Typ oferty</th>
        <th>Typ nieruchomosci</th>
        <th>numer</th>
        <th>powierzchnia</th>
        <th>cena</th>
    </tr>
    </thead>
    <tbody>
    <div id='koszykResult'>
        <?php foreach ($this->koszyk as $k): ?>
            <tr>
                <td><?= $k->id ?></td>
                <td><?= $k->typ_oferty ?></td>
                <td><?= $k->typ_nieruchomosci ?></td>
                <td><?= $k->numer ?></td>
                <td><?= $k->powierzchnia ?></td>
                <td><?= $k->cena ?></td>
                <td>
                <a href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'usun', 'id' => $k->id]) ?>" title="Usuń z koszyka" class="kUsunZKoszyka"><i class="fas fa-trash-alt"></i></a>&nbsp;
                </td>
            </tr>
        <?php endforeach; ?>
    </div>
    </tbody>
</table>