<h1><?= $tytul ?></h1>

<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>
        <table>
        <tr>
            <th>Id:</th>
            <td><?=$ksiazka['id']?></td>
        </tr>
        <tr>
            <th>Id autora:</th>
            <td><?=$ksiazka['id_autora']?></td>
        </tr>
        <tr>
            <th>Tytuł:</th>
            <td><?=$ksiazka['tytul']?></td>
        </tr>
        <tr>
            <th>Cena:</th>
            <td><?=$ksiazka['cena']?></td>
        </tr>
        <tr>
            <th>Liczba stron:</th>
            <td><?=$ksiazka['liczba_stron']?></td>
        </tr>
        </table>


        <?= $this->formSubmit($form->get('zapisz')) ?>

        <?= $this->form()->closeTag($form) ?>
    </div>
</div>